using System;
using System.Collections.Generic;

namespace EasyWord.Models
{
    public partial class 自来水抄表抄表台帐
    {
        public int 抄表台帐编号 { get; set; }
        public bool IsFirst { get; set; }
        public bool IsLast { get; set; }
        public string 用户状态 { get; set; }
        public string 用户编号 { get; set; }
        public string 用户名称 { get; set; }
        public string 用户简码 { get; set; }
        public string 联系电话 { get; set; }
        public string 建档类型 { get; set; }
        public int 顺序号 { get; set; }
        public string 片号 { get; set; }
        public string 区号 { get; set; }
        public string 段号 { get; set; }
        public string 地址 { get; set; }
        public string 小区名称 { get; set; }
        public string 水表安装位置 { get; set; }
        public int? 用水人数 { get; set; }
        public DateTime 收费月份 { get; set; }
        public DateTime 生成台帐日期 { get; set; }
        public DateTime? 抄表录入日期 { get; set; }
        public DateTime? 收款日期 { get; set; }
        public string 收款方式 { get; set; }
        public int 上月用水量 { get; set; }
        public int 上月表数 { get; set; }
        public int 本月表数 { get; set; }
        public int 分表数 { get; set; }
        public int 用水量 { get; set; }
        public bool 是否倒表 { get; set; }
        public bool 增值税用户 { get; set; }
        public string 用水性质分类 { get; set; }
        public string 用水性质编号 { get; set; }
        public string 用水性质名称 { get; set; }
        public decimal 费率水费 { get; set; }
        public decimal 费率污水费 { get; set; }
        public decimal 费率附加费 { get; set; }
        public decimal 费率其它费用 { get; set; }
        public decimal 费率滞纳金 { get; set; }
        public int 结帐日 { get; set; }
        public decimal 应收水费 { get; set; }
        public decimal 应收污水费 { get; set; }
        public decimal 应收附加费 { get; set; }
        public decimal 应收其它费用 { get; set; }
        public decimal 应收小计 { get; set; }
        public decimal 应收滞纳金 { get; set; }
        public decimal 应收合计 { get; set; }
        public decimal 减免收费 { get; set; }
        public decimal 减免滞纳金 { get; set; }
        public decimal 应收实际应收 { get; set; }
        public decimal 实际已收 { get; set; }
        public decimal 本月欠费合计 { get; set; }
        public decimal 期初欠费 { get; set; }
        public decimal 累计欠费 { get; set; }
        public bool 是否预存款 { get; set; }
        public decimal 预存上次预存余额 { get; set; }
        public decimal 预存实缴金额 { get; set; }
        public decimal 预存扣除金额 { get; set; }
        public decimal 预存本月预存 { get; set; }
        public decimal 预存预存余额 { get; set; }
        public decimal 用户余额 { get; set; }
        public int? 台帐生成人员编码 { get; set; }
        public string 台帐生成人员姓名 { get; set; }
        public int? 抄表录入人员编码 { get; set; }
        public string 抄表录入人员姓名 { get; set; }
        public int 抄表人员编码 { get; set; }
        public string 抄表人员姓名 { get; set; }
        public int 收费人员编号 { get; set; }
        public string 收费人员姓名 { get; set; }
        public int 收款人员编号 { get; set; }
        public string 收款人员姓名 { get; set; }
        public string 台帐状态 { get; set; }
        public bool 记帐标志应收 { get; set; }
        public DateTime? 记帐日期应收 { get; set; }
        public string 记帐凭证编号应收 { get; set; }
        public int? 记帐人员编号应收 { get; set; }
        public string 记帐人员名称应收 { get; set; }
        public bool 记帐标志已收 { get; set; }
        public DateTime? 记帐日期已收 { get; set; }
        public string 记帐凭证编号已收 { get; set; }
        public int? 记帐人员编号已收 { get; set; }
        public string 记帐人员名称已收 { get; set; }
        public int? 汇总销号人员编码 { get; set; }
        public string 汇总销号人员姓名 { get; set; }
        public DateTime? 汇总销号日期 { get; set; }
        public bool 发票标志 { get; set; }
        public string 发票编号 { get; set; }
        public bool 发票作废标志 { get; set; }
        public bool 发票销号标志 { get; set; }
        public bool 发票汇总标志 { get; set; }
        public string 发票汇总编号 { get; set; }
        public DateTime? 发票汇总日期 { get; set; }
        public int 发票汇总人员编码 { get; set; }
        public string 发票汇总人员姓名 { get; set; }
        public bool 发票汇总销号标志 { get; set; }
        public decimal? 发票应收水费 { get; set; }
        public decimal? 发票应收附加费 { get; set; }
        public decimal? 发票应收污水费 { get; set; }
        public decimal? 发票应收其它费用 { get; set; }
        public decimal? 发票应收滞纳金 { get; set; }
        public decimal? 发票应收合计 { get; set; }
        public int? 发票上次表数 { get; set; }
        public int? 发票本次表数 { get; set; }
        public int? 发票分表数 { get; set; }
        public int? 发票用水量 { get; set; }
    }
}
